# Bem vindo a Jekyll!
#
# Este arquivo de configuração é destinado para configurações que afetam seu blog
# inteiro, valores que você espera configurar uma vez e raramente precisa editar
# após isto.
# Por razões técnicas, este arquivo *NÂO* é recarregado automaticamente quando
# você usa 'jekyll serve'. Se você mudar este arquivo, por favor, reinicie o
# processo do servidor.

# Configurações do site
title: História da Computação
email: juniorabreuantispam@outlook.com
description: > # Isto significa ignorar quebras de linhas até "baseurl:"
  Webjeda Cards é um tema jekyll baseado em Bootstrap para portfólio, fotografia ou qualquer tipo de blog.



baseurl: "/blog-history" # O subcaminho de seu site, e.g. /blog
url: "https://juniorcesarabreu.tk" # O nome de domínio & protocolo para seu site

#sidebar
default-image: webjeda-logo-big.jpg # Se há nenhuma imagem de destaque em um post então esta imagem será exibida. Também em todas as páginas esta imagem será exibida. Use uma imagem 500x250.

#footer
built-by: webjeda
copyright:
   name: webjeda
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics:

# Comments
disqus-shortname: juniorcesarabreu

#social
facebook: http://facebook.com/juniorcesarabreu.sg
quora: http://quora.com/juniorcesarabreu
twitter: http://twitter.com/@juniorcesarsg
github: http://github.com/juniorcesarabreu

#facebook like box
#fb-app-id: 0000000000
fb-page-url: https://www.facebook.com/juniorcesarabreu.sg/
fb-page-title: juniorcesarabreu

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
